### ISSUE TITLE
Package requires pandasgui

### ISSUE THREAD

**Issue by AllyTally** [adamerose/QStylish#3]
The package itself doesn't seem to use `pandasgui` at all; however the demo widget does. Can you remove this requirement?

**Comment by adamerose** [comment]
Didn't see `pandasgui` in `setup.py` or `requirements.txt`, and the demo widget already puts the `pandasgui` inside a try/pass block. I did notice the version number was incorrectly based on pandasgui though and fixed that. If you still have this issue update to the latest version and let me know which file the problem is in
